[profile.default]
src = 'src'
libs = ['lib']
fs_permissions = [{ access = 'read-write', path = '/'}]
ffi = true
solc_version = '0.8.23'
evm_version = 'shanghai'


remappings = [
    "forge-std=lib/forge-std/src",
    "forge-ctf=lib/forge-ctf/src",
]

# See more config options https://github.com/foundry-rs/foundry/tree/master/config