[package]
name = "ctf"
version = "0.1.0"

# See more keys and their definitions at https://docs.swmansion.com/scarb/docs/reference/manifest.html

[dependencies]
# This is not recommended for production code, only use the latest relase of the openzeppelin package
# instead of the main branch.
openzeppelin = { git = "https://github.com/OpenZeppelin/cairo-contracts.git", branch = "main" }
starknet = "2.5.3"

[lib]

[[target.starknet-contract]]
allowed-libfuncs-list.name = "experimental"
sierra = true
casm = true
casm-add-pythonic-hints = true

[tool.fmt]
sort-module-level-items = true
